### ISSUE TITLE
searchp --output-columns option with taxonomy columns

### ISSUE THREAD

**Issue by uludag** [seqan/lambda#116] opened 2018-02-20 16:15 UTC
I downloaded prebuild UniProt index using the link given on the pre-build indexes [wiki](https://github.com/seqan/lambda/wiki/Pre-built-Database-Indexes) page where Tax option is checked for the index.

If I add  `staxids` or `lcaid` options to `--output-columns` specifier such as `"std staxids"`, I get _too-many-arguments_ error. Taxonomic-Workflows wiki [page](https://github.com/seqan/lambda/wiki/Taxonomic-Workflows) suggests combined column options should work. If I specify `staxids` or `lcaid` options alone I don't get any errors.  --mahmut

**Comment by h-2** [comment] 2018-02-20 22:18
I am currently on vacation and will have a look at this next week in detail. However, please check if single quotes work instead of double quotes, i.e. `--output-columns 'std qacc'`. Depending on your shell or your shell-script this might make a difference.

**Comment by uludag** [comment] 2018-02-21 06:32
I have checked that single quotes, i.e. `--output-columns 'std qacc'` doesn't change the error message returned

**Comment by h-2** [comment] 2018-04-04 12:02
Sorry for the late reply. I have tried to reproduce the issue, but everything works fine here.
Can you give me the following information:

* output of `uname -a`
* contents of `/etc/debian_version` if it exists
* output of `$SHELL --version`
* output of `bin/lambda2 --version`

Thanks and sorry again for the late reply.

**Comment by uludag** [comment] 2018-04-05 15:50
I just have found that above error is limited to the lambda2 executable in lambda2-1.9.4-Linux-x86_64.tar.xz. It looks I don't get error if I use the lambda2 executable, version 1.9.4, compiled on my machine earlier

I don't have `/etc/debian_version` on my machine

I select/copied the outputs you asked here:
> Linux 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017
> GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
> lambda2 version: 1.9.4
> SeqAn version: 2.4.0

**Comment by h-2** [comment] 2018-04-08 17:26
I can confirm the issue, it's due to some problem in the argument parser related to static builds, I will try to track it down next week!

**Comment by h-2** [comment] 2018-04-09 16:07
Should be fixed in current master!

**Closed by h-2** 2018-04-09 16:07 UTC
Labels: bug

**Comment by h-2** [comment] 2018-04-09 16:08
(it wasn't the argument parser after all, but the my shell script that dispatches to the binaries :see_no_evil: )
